I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
*** glibc detected *** python: free(): invalid next size (normal): 0x00000000021f2300 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30c6675e66]
/lib64/libc.so.6[0x30c66789b3]
python[0x44b7e7]
python(PyDict_SetItem+0x89)[0x44ede9]
python(_PyModule_Clear+0x14e)[0x45061e]
python(PyImport_Cleanup+0x437)[0x4bd9e7]
python(Py_Finalize+0xff)[0x4cb9ef]
python(Py_Main+0x533)[0x414b23]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30c661ed5d]
python[0x4141f9]
======= Memory map: ========






/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 31: 19914 Aborted                 (core dumped) python -m himanshu.nn.sklearn_hotcold -state=22 --include_0








I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
*** glibc detected *** python: free(): invalid next size (normal): 0x0000000002412300 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30c6675e66]
/lib64/libc.so.6[0x30c66789b3]
python[0x44b7e7]
python(PyDict_SetItem+0x89)[0x44ede9]
python(_PyModule_Clear+0x14e)[0x45061e]
python(PyImport_Cleanup+0x437)[0x4bd9e7]
python(Py_Finalize+0xff)[0x4cb9ef]
python(Py_Main+0x533)[0x414b23]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30c661ed5d]
python[0x4141f9]
======= Memory map: ========

/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 37:  7784 Aborted                 (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=1 --include_0
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
*** glibc detected *** python: free(): invalid next size (normal): 0x000000000179e300 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30c6675e66]
/lib64/libc.so.6[0x30c66789b3]
python[0x44b7e7]
python(PyDict_SetItem+0x89)[0x44ede9]
python(_PyModule_Clear+0x14e)[0x45061e]
python(PyImport_Cleanup+0x437)[0x4bd9e7]
python(Py_Finalize+0xff)[0x4cb9ef]
python(Py_Main+0x533)[0x414b23]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30c661ed5d]
python[0x4141f9]
======= Memory map: ========

/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 38: 10309 Aborted                 (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=2 --include_0
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
*** glibc detected *** python: free(): invalid next size (normal): 0x00000000027f8300 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30c6675e66]
/lib64/libc.so.6[0x30c66789b3]
python[0x44b7e7]
python(PyDict_SetItem+0x89)[0x44ede9]
python(_PyModule_Clear+0x14e)[0x45061e]
python(PyImport_Cleanup+0x437)[0x4bd9e7]
python(Py_Finalize+0xff)[0x4cb9ef]
python(Py_Main+0x533)[0x414b23]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30c661ed5d]
python[0x4141f9]
======= Memory map: ========

/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 39: 13034 Aborted                 (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=3 --include_0
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
*** glibc detected *** python: free(): invalid next size (normal): 0x0000000001011300 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30c6675e66]
/lib64/libc.so.6[0x30c66789b3]
python[0x44b7e7]
python(PyDict_SetItem+0x89)[0x44ede9]
python(_PyModule_Clear+0x14e)[0x45061e]
python(PyImport_Cleanup+0x437)[0x4bd9e7]
python(Py_Finalize+0xff)[0x4cb9ef]
python(Py_Main+0x533)[0x414b23]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30c661ed5d]
python[0x4141f9]
======= Memory map: ========

/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 40: 14107 Aborted                 (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=4 --include_0
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
*** glibc detected *** python: free(): invalid next size (normal): 0x0000000001a33300 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30c6675e66]
/lib64/libc.so.6[0x30c66789b3]
python[0x44b7e7]
python(PyDict_SetItem+0x89)[0x44ede9]
python(_PyModule_Clear+0x14e)[0x45061e]
python(PyImport_Cleanup+0x437)[0x4bd9e7]
python(Py_Finalize+0xff)[0x4cb9ef]
python(Py_Main+0x533)[0x414b23]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30c661ed5d]
python[0x4141f9]
======= Memory map: ========

/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 41: 15998 Aborted                 (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=5 --include_0
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
*** glibc detected *** python: free(): invalid next size (normal): 0x0000000000903300 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30c6675e66]
/lib64/libc.so.6[0x30c66789b3]
python[0x44b7e7]
python(PyDict_SetItem+0x89)[0x44ede9]
python(_PyModule_Clear+0x14e)[0x45061e]
python(PyImport_Cleanup+0x437)[0x4bd9e7]
python(Py_Finalize+0xff)[0x4cb9ef]
python(Py_Main+0x533)[0x414b23]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30c661ed5d]
python[0x4141f9]
======= Memory map: ========

/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 42: 16916 Aborted                 (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=6 --include_0
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
*** glibc detected *** python: free(): invalid next size (normal): 0x0000000001a70300 ***
======= Backtrace: =========
/lib64/libc.so.6[0x30c6675e66]
/lib64/libc.so.6[0x30c66789b3]
python[0x44b7e7]
python(PyDict_SetItem+0x89)[0x44ede9]
python(_PyModule_Clear+0x14e)[0x45061e]
python(PyImport_Cleanup+0x437)[0x4bd9e7]
python(Py_Finalize+0xff)[0x4cb9ef]
python(Py_Main+0x533)[0x414b23]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x30c661ed5d]
python[0x4141f9]
======= Memory map: ========

/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 43: 19438 Aborted                 (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=7 --include_0
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 55: 31294 Segmentation fault      (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=1
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 56:  1385 Segmentation fault      (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=2
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 57:  4272 Segmentation fault      (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=3
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 58:  5190 Segmentation fault      (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=4
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 59:  6756 Segmentation fault      (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=5
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 60:  8000 Segmentation fault      (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=6
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
/var/spool/PBS/mom_priv/jobs/337491.hn1.hpc.iitd.ac.in.SC: line 61: 10559 Segmentation fault      (core dumped) python -m himanshu.nn.sklearn_train -state=22 -label=7
